@startuml
actor admin as "Admin"
view --> admin : tampilan dashboard
admin -> view : pilih menu buat jadwal
view -> controller : request menu buat jadwal
controller -> model : ambil data jadwal
model --> controller : return data jadwal
controller --> view : ambil konten
view --> admin : tampilkan data jadwal
admin -> view : buat jadwal
view -> controller : request simpan jadwal
controller -> model : simpan data jadwal
@enduml