@startuml buat_jadwal

(*) --> Buka dashboard admin
--> pilih menu buat jadwal
--> pilih Dosen
--> pilih mata kuiah
--> pilih waktu
--> muncul daftar ruangan untuk rentang jam tersebut
if "ruangan sudah terisi?" then
    --> [terisi] disabled nama kelas (tidak bisa dipilih)
else
    --> [kosong] pilih kelas
endif
--> simpan
--> (*)

@enduml